from app.models import db, User, environment, SCHEMA
from sqlalchemy.sql import text


# Adds a demo user, you can add other users here if you want
def seed_users():

    users = [
        User(
            id=1,
            first_name="John",
            last_name="Doe",
            username="johndoe",
            email="john.doe@example.com",
            phone_number="5551230001",
            image_url="http://example.com/images/johndoe.jpg",
            password="password"
        ),
        User(
            id=2,
            first_name="Jane",
            last_name="Doe",
            username="janedoe",
            email="jane.doe@example.com",
            phone_number="5551230002",
            image_url="http://example.com/images/janedoe.jpg",
            password="password"
        ),
        User(
            id=3,
            first_name="Alice",
            last_name="Smith",
            username="alicesmith",
            email="alice.smith@example.com",
            phone_number="5551230003",
            image_url="http://example.com/images/alicesmith.jpg",
            password="password"
        ),
        User(
            id=4,
            first_name="Bob",
            last_name="Brown",
            username="bobbrown",
            email="bob.brown@example.com",
            phone_number="5551230004",
            image_url="http://example.com/images/bobbrown.jpg",
            password="password"
        ),
        User(
            id=5,
            first_name="Charlie",
            last_name="Davis",
            username="charliedavis",
            email="charlie.davis@example.com",
            phone_number="5551230005",
            image_url="http://example.com/images/charliedavis.jpg",
            password="password"
        ),
        User(
            id=6,
            first_name="David",
            last_name="Wilson",
            username="davidwilson",
            email="david.wilson@example.com",
            phone_number="5551230006",
            image_url="http://example.com/images/davidwilson.jpg",
            password="password"
        ),
        User(
            id=7,
            first_name="Eva",
            last_name="Martin",
            username="evamartin",
            email="eva.martin@example.com",
            phone_number="5551230007",
            image_url="http://example.com/images/evamartin.jpg",
            password="password"
        ),
        User(
            id=8,
            first_name="Frank",
            last_name="Thompson",
            username="frankthompson",
            email="frank.thompson@example.com",
            phone_number="5551230008",
            image_url="http://example.com/images/frankthompson.jpg",
            password="password"
        ),
        User(
            id=9,
            first_name="Grace",
            last_name="White",
            username="gracewhite",
            email="grace.white@example.com",
            phone_number="5551230009",
            image_url="http://example.com/images/gracewhite.jpg",
            password="password"
        ),
        User(
            id=10,
            first_name="Hank",
            last_name="Lee",
            username="hanklee",
            email="hank.lee@example.com",
            phone_number="5551230010",
            image_url="http://example.com/images/hanklee.jpg",
            password="password"
        ),
        User(
            id=11,
            first_name="Ivy",
            last_name="Clark",
            username="ivyclark",
            email="ivy.clark@example.com",
            phone_number="5551230011",
            image_url="http://example.com/images/ivyclark.jpg",
            password="password"
        ),
        User(
            id=12,
            first_name="Jack",
            last_name="Walker",
            username="jackwalker",
            email="jack.walker@example.com",
            phone_number="5551230012",
            image_url="http://example.com/images/jackwalker.jpg",
            password="password"
        ),
        User(
            id=13,
            first_name="Kara",
            last_name="Hall",
            username="karahall",
            email="kara.hall@example.com",
            phone_number="5551230013",
            image_url="http://example.com/images/karahall.jpg",
            password="password"
        ),
        User(
            id=14,
            first_name="Leo",
            last_name="Allen",
            username="leoallen",
            email="leo.allen@example.com",
            phone_number="5551230014",
            image_url="http://example.com/images/leoallen.jpg",
            password="password"
        ),
        User(
            id=15,
            first_name="Mia",
            last_name="Young",
            username="miayoung",
            email="mia.young@example.com",
            phone_number="5551230015",
            image_url="http://example.com/images/miayoung.jpg",
            password="password"
        ),
        User(
            id=16,
            first_name="Nina",
            last_name="King",
            username="ninaking",
            email="nina.king@example.com",
            phone_number="5551230016",
            image_url="http://example.com/images/ninaking.jpg",
            password="password"
        ),
        User(
            id=17,
            first_name="Oscar",
            last_name="Scott",
            username="oscarscott",
            email="oscar.scott@example.com",
            phone_number="5551230017",
            image_url="http://example.com/images/oscarscott.jpg",
            password="password"
        ),
        User(
            id=18,
            first_name="Paula",
            last_name="Adams",
            username="paulaadams",
            email="paula.adams@example.com",
            phone_number="5551230018",
            image_url="http://example.com/images/paulaadams.jpg",
            password="password"
        ),
        User(
            id=19,
            first_name="Quincy",
            last_name="Baker",
            username="quincybaker",
            email="quincy.baker@example.com",
            phone_number="5551230019",
            image_url="http://example.com/images/quincybaker.jpg",
            password="password"
        ),
        User(
            id=20,
            first_name="Rita",
            last_name="Gonzalez",
            username="ritagonzalez",
            email="rita.gonzalez@example.com",
            phone_number="5551230020",
            image_url="http://example.com/images/ritagonzalez.jpg",
            password="password"
        ),
        User(
            id=21,
            first_name="Sam",
            last_name="Nelson",
            username="samnelson",
            email="sam.nelson@example.com",
            phone_number="5551230021",
            image_url="http://example.com/images/samnelson.jpg",
            password="password"
        ),
        User(
            id=22,
            first_name="Tina",
            last_name="Carter",
            username="tinacarter",
            email="tina.carter@example.com",
            phone_number="5551230022",
            image_url="http://example.com/images/tinacarter.jpg",
            password="password"
        ),
        User(
            id=23,
            first_name="Ulysses",
            last_name="Mitchell",
            username="ulyssesmitchell",
            email="ulysses.mitchell@example.com",
            phone_number="5551230023",
            image_url="http://example.com/images/ulyssesmitchell.jpg",
            password="password"
        ),
        User(
            id=24,
            first_name="Vera",
            last_name="Perez",
            username="veraperez",
            email="vera.perez@example.com",
            phone_number="5551230024",
            image_url="http://example.com/images/veraperez.jpg",
            password="password"
        ),
        User(
            id=25,
            first_name="Will",
            last_name="Ramirez",
            username="willramirez",
            email="will.ramirez@example.com",
            phone_number="5551230025",
            image_url="http://example.com/images/willramirez.jpg",
            password="password"
        ),
        User(
            id=26,
            first_name="Xena",
            last_name="Hughes",
            username="xenahughes",
            email="xena.hughes@example.com",
            phone_number="5551230026",
            image_url="http://example.com/images/xenahughes.jpg",
            password="password"
        ),
        User(
            id=27,
            first_name="Yale",
            last_name="Ross",
            username="yaleross",
            email="yale.ross@example.com",
            phone_number="5551230027",
            image_url="http://example.com/images/yaleross.jpg",
            password="password"
        ),
        User(
            id=28,
            first_name="Zara",
            last_name="Cruz",
            username="zaracruz",
            email="zara.cruz@example.com",
            phone_number="5551230028",
            image_url="http://example.com/images/zaracruz.jpg",
            password="password"
        ),
        User(
            id=29,
            first_name="Adam",
            last_name="Simmons",
            username="adamsimmons",
            email="adam.simmons@example.com",
            phone_number="5551230029",
            image_url="http://example.com/images/adamsimmons.jpg",
            password="password"
        ),
        User(
            id=30,
            first_name="Bella",
            last_name="Morris",
            username="bellamorris",
            email="bella.morris@example.com",
            phone_number="5551230030",
            image_url="http://example.com/images/bellamorris.jpg",
            password="password"
        )
    ]

    # Add each user to the session and commit\
    db.session.bulk_save_objects(users)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_users():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM users"))

    db.session.commit()
