from app.models import db, User, environment, SCHEMA
from sqlalchemy.sql import text


# Adds a demo user, you can add other users here if you want
def seed_users():

    users = [
        User(
            first_name="John",
            last_name="Doe",
            username="johndoe",
            email="john.doe@example.com",
            phone_number="5551230001",
            password="password"
        ),
        User(
            first_name="Jane",
            last_name="Doe",
            username="janedoe",
            email="jane.doe@example.com",
            phone_number="5551230002",
            password="password"
        ),
        User(
            first_name="Alice",
            last_name="Smith",
            username="alicesmith",
            email="alice.smith@example.com",
            phone_number="5551230003",
            password="password"
        ),
        User(
            first_name="Bob",
            last_name="Brown",
            username="bobbrown",
            email="bob.brown@example.com",
            phone_number="5551230004",
            password="password"
        ),
        User(
            first_name="Charlie",
            last_name="Davis",
            username="charliedavis",
            email="charlie.davis@example.com",
            phone_number="5551230005",
            password="password"
        ),
        User(
            first_name="David",
            last_name="Wilson",
            username="davidwilson",
            email="david.wilson@example.com",
            phone_number="5551230006",
            password="password"
        ),
        User(
            first_name="Eva",
            last_name="Martin",
            username="evamartin",
            email="eva.martin@example.com",
            phone_number="5551230007",
            password="password"
        ),
        User(
            first_name="Frank",
            last_name="Thompson",
            username="frankthompson",
            email="frank.thompson@example.com",
            phone_number="5551230008",
            password="password"
        ),
        User(
            first_name="Grace",
            last_name="White",
            username="gracewhite",
            email="grace.white@example.com",
            phone_number="5551230009",
            password="password"
        ),
        User(
            first_name="Hank",
            last_name="Lee",
            username="hanklee",
            email="hank.lee@example.com",
            phone_number="5551230010",
            password="password"
        ),
        User(
            first_name="Ivy",
            last_name="Clark",
            username="ivyclark",
            email="ivy.clark@example.com",
            phone_number="5551230011",
            password="password"
        ),
        User(
            first_name="Jack",
            last_name="Walker",
            username="jackwalker",
            email="jack.walker@example.com",
            phone_number="5551230012",
            password="password"
        ),
        User(
            first_name="Kara",
            last_name="Hall",
            username="karahall",
            email="kara.hall@example.com",
            phone_number="5551230013",
            password="password"
        ),
        User(
            first_name="Leo",
            last_name="Allen",
            username="leoallen",
            email="leo.allen@example.com",
            phone_number="5551230014",
            password="password"
        ),
        User(
            first_name="Mia",
            last_name="Young",
            username="miayoung",
            email="mia.young@example.com",
            phone_number="5551230015",
            password="password"
        ),
        User(
            first_name="Nina",
            last_name="King",
            username="ninaking",
            email="nina.king@example.com",
            phone_number="5551230016",
            password="password"
        ),
        User(
            first_name="Oscar",
            last_name="Scott",
            username="oscarscott",
            email="oscar.scott@example.com",
            phone_number="5551230017",
            password="password"
        ),
        User(
            first_name="Paula",
            last_name="Adams",
            username="paulaadams",
            email="paula.adams@example.com",
            phone_number="5551230018",
            password="password"
        ),
        User(
            first_name="Quincy",
            last_name="Baker",
            username="quincybaker",
            email="quincy.baker@example.com",
            phone_number="5551230019",
            password="password"
        ),
        User(
            first_name="Rita",
            last_name="Gonzalez",
            username="ritagonzalez",
            email="rita.gonzalez@example.com",
            phone_number="5551230020",
            password="password"
        ),
        User(
            first_name="Sam",
            last_name="Nelson",
            username="samnelson",
            email="sam.nelson@example.com",
            phone_number="5551230021",
            password="password"
        ),
        User(
            first_name="Tina",
            last_name="Carter",
            username="tinacarter",
            email="tina.carter@example.com",
            phone_number="5551230022",
            password="password"
        ),
        User(
            first_name="Ulysses",
            last_name="Mitchell",
            username="ulyssesmitchell",
            email="ulysses.mitchell@example.com",
            phone_number="5551230023",
            password="password"
        ),
        User(
            first_name="Vera",
            last_name="Perez",
            username="veraperez",
            email="vera.perez@example.com",
            phone_number="5551230024",
            password="password"
        ),
        User(
            first_name="Will",
            last_name="Ramirez",
            username="willramirez",
            email="will.ramirez@example.com",
            phone_number="5551230025",
            password="password"
        ),
        User(
            first_name="Xena",
            last_name="Hughes",
            username="xenahughes",
            email="xena.hughes@example.com",
            phone_number="5551230026",
            password="password"
        ),
        User(
            first_name="Yale",
            last_name="Ross",
            username="yaleross",
            email="yale.ross@example.com",
            phone_number="5551230027",
            password="password"
        ),
        User(
            first_name="Zara",
            last_name="Cruz",
            username="zaracruz",
            email="zara.cruz@example.com",
            phone_number="5551230028",
            password="password"
        ),
        User(
            first_name="Adam",
            last_name="Simmons",
            username="adamsimmons",
            email="adam.simmons@example.com",
            phone_number="5551230029",
            password="password"
        ),
        User(
            first_name="Bella",
            last_name="Morris",
            username="bellamorris",
            email="bella.morris@example.com",
            phone_number="5551230030",
            password="password"
        )
    ]

    # Add each user to the session and commit\
    db.session.bulk_save_objects(users)
    db.session.commit()


# Uses a raw SQL query to TRUNCATE or DELETE the users table. SQLAlchemy doesn't
# have a built in function to do this. With postgres in production TRUNCATE
# removes all the data from the table, and RESET IDENTITY resets the auto
# incrementing primary key, CASCADE deletes any dependent entities.  With
# sqlite3 in development you need to instead use DELETE to remove all data and
# it will reset the primary keys for you as well.
def undo_users():
    if environment == "production":
        db.session.execute(f"TRUNCATE table {SCHEMA}.users RESTART IDENTITY CASCADE;")
    else:
        db.session.execute(text("DELETE FROM users"))

    db.session.commit()
