"""updated models

Revision ID: 4659ba6aad77
Revises: 089a021d2f25
Create Date: 2024-08-22 18:07:58.990720

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4659ba6aad77'
down_revision = '089a021d2f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=225), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=225), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
