"""Changed Numeric Values on Players Model to make the range bigger to fix Render deployment

Revision ID: a8bdb1438761
Revises: 4659ba6aad77
Create Date: 2024-08-23 10:47:34.921544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bdb1438761'
down_revision = '4659ba6aad77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('average_draft_position',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('points_last_season',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('points_last_season',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=False)
        batch_op.alter_column('average_draft_position',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=2, scale=1),
               existing_nullable=False)

    # ### end Alembic commands ###
