"""updated password varchar length validation from 35 to 225

Revision ID: b5f008d97ff5
Revises: 8abadac669c4
Create Date: 2024-08-31 14:43:40.564425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5f008d97ff5'
down_revision = '8abadac669c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=225),
               existing_nullable=False)
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(length=35),
               type_=sa.String(length=225),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('hashed_password',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=35),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
