"""Removed image_url from Users table

Revision ID: c64255209fce
Revises: b195a056b48d
Create Date: 2024-09-03 03:30:32.987237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c64255209fce'
down_revision = 'b195a056b48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=225),
               existing_nullable=True)

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=225), nullable=True))

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('team',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    with op.batch_alter_table('leagues', schema=None) as batch_op:
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
